name: Release

on:
  release:
    types: published

jobs:
  release-3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      name: Android Debug CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [debug]
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Prepare token.properties file
        run: |
          if [ -f "$GITHUB_WORKSPACE/token.properties" ]; then
            rm $GITHUB_WORKSPACE/token.properties
          fi
          echo "VCSPACE_TOKEN=${{ secrets.VCSPACE_TOKEN }}" >> $GITHUB_WORKSPACE/token.properties
          echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> $GITHUB_WORKSPACE/token.properties
          echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> $GITHUB_WORKSPACE/token.properties
          echo "OAUTH_REDIRECT_URL=${{ secrets.OAUTH_REDIRECT_URL }}" >> $GITHUB_WORKSPACE/token.properties

      - name: Debug token.properties creation
        run: ls -la $GITHUB_WORKSPACE

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give permission to executable
        run: chmod +x gradlew

      - name: Generate APK
        run: ./gradlew assemble${{ matrix.build-type }}

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: app-${{ matrix.build-type }}
          path: app/build/outputs/apk/${{ matrix.build-type }}/app-${{ matrix.build-type }}.apk
      
#
#            -F message_thread_id="${{ secrets.RELEASE_TOPIC_ID }}" \
#            -F caption="${{ github.event.head_commit.message }} by ${{ github.actor }}" \
#            -F document=@"app/build/outputs/apk/release/app-release.apk"
#      - run: ./gradlew :sbp-core:publish -Pversion=3.3.${GITHUB_REF##*/} -P'signing.keyId=${{ secrets.signingKeyId }}' -P'signing.password=${{ secrets.signingPassword }}' -P'sonatypeUsername=${{ secrets.sonatypeUsername }}' -P'sonatypePassword=${{ secrets.sonatypePassword }}'
##      - run: ./gradlew :sbp-spring-boot-starter:publish -Pversion=3.3.${GITHUB_REF##*/} -P'signing.keyId=${{ secrets.signingKeyId }}' -P'signing.password=${{ secrets.signingPassword }}' -P'sonatypeUsername=${{ secrets.sonatypeUsername }}' -P'sonatypePassword=${{ secrets.sonatypePassword }}'
#      - run: ./gradlew :sbp-adapter-3:publish -Pversion=3.3.${GITHUB_REF##*/} -P'signing.keyId=${{ secrets.signingKeyId }}' -P'signing.password=${{ secrets.signingPassword }}' -P'sonatypeUsername=${{ secrets.sonatypeUsername }}' -P'sonatypePassword=${{ secrets.sonatypePassword }}'
#      - run: ./gradlew :sbp-spring-boot-jpa-starter:publish -Pversion=3.3.${GITHUB_REF##*/} -P'signing.keyId=${{ secrets.signingKeyId }}' -P'signing.password=${{ secrets.signingPassword }}' -P'sonatypeUsername=${{ secrets.sonatypeUsername }}' -P'sonatypePassword=${{ secrets.sonatypePassword }}'
 #     - run: ./gradlew :sbp-spring-boot-springdoc-starter:publish -Pversion=3.3.${GITHUB_REF##*/} -P'signing.keyId=${{ secrets.signingKeyId }}' -P'signing.password=${{ secrets.signingPassword }}' -P'sonatypeUsername=${{ secrets.sonatypeUsername }}' -P'sonatypePassword=${{ secrets.sonatypePassword }}'
